tblCategoriesNumberSmall1 = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesNumberSmall1') === true && tblCategoriesDataObject._tblCategoriesNumberSmall1 ? FunctionsGeneric.valueMaskWrite(tblCategoriesDataObject._tblCategoriesNumberSmall1, gSystemConfig.configCategoriesNumberS1FieldType) : tblCategoriesNumberSmall1;
tblCategoriesNumberSmall2 = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesNumberSmall2') === true && tblCategoriesDataObject._tblCategoriesNumberSmall2 ? FunctionsGeneric.valueMaskWrite(tblCategoriesDataObject._tblCategoriesNumberSmall2, gSystemConfig.configCategoriesNumberS2FieldType) : tblCategoriesNumberSmall2;
tblCategoriesNumberSmall3 = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesNumberSmall3') === true && tblCategoriesDataObject._tblCategoriesNumberSmall3 ? FunctionsGeneric.valueMaskWrite(tblCategoriesDataObject._tblCategoriesNumberSmall3, gSystemConfig.configCategoriesNumberS3FieldType) : tblCategoriesNumberSmall3;
tblCategoriesNumberSmall4 = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesNumberSmall4') === true && tblCategoriesDataObject._tblCategoriesNumberSmall4 ? FunctionsGeneric.valueMaskWrite(tblCategoriesDataObject._tblCategoriesNumberSmall4, gSystemConfig.configCategoriesNumberS4FieldType) : tblCategoriesNumberSmall4;
tblCategoriesNumberSmall5 = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesNumberSmall5') === true && tblCategoriesDataObject._tblCategoriesNumberSmall5 ? FunctionsGeneric.valueMaskWrite(tblCategoriesDataObject._tblCategoriesNumberSmall5, gSystemConfig.configCategoriesNumberS5FieldType) : tblCategoriesNumberSmall5;

tblCategoriesDate1 = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesDate1') === true && tblCategoriesDataObject._tblCategoriesDate1 ? FunctionsGeneric.dateSQLWrite(tblCategoriesDataObject._tblCategoriesDate1, gSystemConfig.configBackendDateFormat) : tblCategoriesDate1;
tblCategoriesDate2 = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesDate2') === true && tblCategoriesDataObject._tblCategoriesDate2 ? FunctionsGeneric.dateSQLWrite(tblCategoriesDataObject._tblCategoriesDate2, gSystemConfig.configBackendDateFormat) : tblCategoriesDate2;
tblCategoriesDate3 = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesDate3') === true && tblCategoriesDataObject._tblCategoriesDate3 ? FunctionsGeneric.dateSQLWrite(tblCategoriesDataObject._tblCategoriesDate3, gSystemConfig.configBackendDateFormat) : tblCategoriesDate3;
tblCategoriesDate4 = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesDate4') === true && tblCategoriesDataObject._tblCategoriesDate4 ? FunctionsGeneric.dateSQLWrite(tblCategoriesDataObject._tblCategoriesDate4, gSystemConfig.configBackendDateFormat) : tblCategoriesDate4;
tblCategoriesDate5 = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesDate5') === true && tblCategoriesDataObject._tblCategoriesDate5 ? FunctionsGeneric.dateSQLWrite(tblCategoriesDataObject._tblCategoriesDate5, gSystemConfig.configBackendDateFormat) : tblCategoriesDate5;

tblCategoriesIdItem1 = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesIdItem1') === true && tblCategoriesDataObject._tblCategoriesIdItem1 ? tblCategoriesDataObject._tblCategoriesIdItem1 : tblCategoriesIdItem1;
tblCategoriesIdItem2 = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesIdItem2') === true && tblCategoriesDataObject._tblCategoriesIdItem2 ? tblCategoriesDataObject._tblCategoriesIdItem2 : tblCategoriesIdItem2;
tblCategoriesIdItem3 = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesIdItem3') === true && tblCategoriesDataObject._tblCategoriesIdItem3 ? tblCategoriesDataObject._tblCategoriesIdItem3 : tblCategoriesIdItem3;
tblCategoriesIdItem4 = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesIdItem4') === true && tblCategoriesDataObject._tblCategoriesIdItem4 ? tblCategoriesDataObject._tblCategoriesIdItem4 : tblCategoriesIdItem4;
tblCategoriesIdItem5 = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesIdItem5') === true && tblCategoriesDataObject._tblCategoriesIdItem5 ? tblCategoriesDataObject._tblCategoriesIdItem5 : tblCategoriesIdItem5;

tblCategoriesImageMain = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesImageMain') === true ? tblCategoriesDataObject._tblCategoriesImageMain : tblCategoriesImageMain;
tblCategoriesFile1 = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesFile1') === true ? tblCategoriesDataObject._tblCategoriesFile1 : tblCategoriesFile1;
tblCategoriesFile2 = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesFile2') === true ? tblCategoriesDataObject._tblCategoriesFile2 : tblCategoriesFile2;
tblCategoriesFile3 = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesFile3') === true ? tblCategoriesDataObject._tblCategoriesFile3 : tblCategoriesFile3;
tblCategoriesFile4 = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesFile4') === true ? tblCategoriesDataObject._tblCategoriesFile4 : tblCategoriesFile4;
tblCategoriesFile5 = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesFile5') === true ? tblCategoriesDataObject._tblCategoriesFile5 : tblCategoriesFile5;

tblCategoriesActivation = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesActivation') === true && tblCategoriesDataObject._tblCategoriesActivation ? tblCategoriesDataObject._tblCategoriesActivation : tblCategoriesActivation;
tblCategoriesActivation1 = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesActivation1') === true && tblCategoriesDataObject._tblCategoriesActivation1 ? tblCategoriesDataObject._tblCategoriesActivation1 : tblCategoriesActivation1;
tblCategoriesActivation2 = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesActivation2') === true && tblCategoriesDataObject._tblCategoriesActivation2 ? tblCategoriesDataObject._tblCategoriesActivation2 : tblCategoriesActivation2;
tblCategoriesActivation3 = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesActivation3') === true && tblCategoriesDataObject._tblCategoriesActivation3 ? tblCategoriesDataObject._tblCategoriesActivation3 : tblCategoriesActivation3;
tblCategoriesActivation4 = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesActivation5') === true && tblCategoriesDataObject._tblCategoriesActivation4 ? tblCategoriesDataObject._tblCategoriesActivation4 : tblCategoriesActivation5;
tblCategoriesActivation5 = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesActivation5') === true && tblCategoriesDataObject._tblCategoriesActivation5 ? tblCategoriesDataObject._tblCategoriesActivation5 : tblCategoriesActivation5;

tblCategoriesIdStatus = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesIdStatus') === true && tblCategoriesDataObject._tblCategoriesIdStatus ? tblCategoriesDataObject._tblCategoriesIdStatus : tblCategoriesIdStatus;
tblCategoriesRestrictedAccess = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesRestrictedAccess') === true && tblCategoriesDataObject._tblCategoriesRestrictedAccess ? tblCategoriesDataObject._tblCategoriesRestrictedAccess : tblCategoriesRestrictedAccess;

// tblCategoriesNotes = (tblCategoriesDataObject.hasOwnProperty('_tblCategoriesNotes') === true) ? tblCategoriesDataObject._tblCategoriesNotes : tblCategoriesNotes;
tblCategoriesNotes = tblCategoriesDataObject.hasOwnProperty('_tblCategoriesNotes') === true ? FunctionsGeneric.contentMaskWrite(tblCategoriesDataObject._tblCategoriesNotes, 'db_write_text') : tblCategoriesNotes;

arrIdsCategoriesFiltersGeneric1 = tblCategoriesDataObject.hasOwnProperty('_arrIdsCategoriesFiltersGeneric1') === true && tblCategoriesDataObject._arrIdsCategoriesFiltersGeneric1 ? tblCategoriesDataObject._arrIdsCategoriesFiltersGeneric1 : arrIdsCategoriesFiltersGeneric1;
arrIdsCategoriesFiltersGeneric2 = tblCategoriesDataObject.hasOwnProperty('_arrIdsCategoriesFiltersGeneric2') === true && tblCategoriesDataObject._arrIdsCategoriesFiltersGeneric2 ? tblCategoriesDataObject._arrIdsCategoriesFiltersGeneric2 : arrIdsCategoriesFiltersGeneric2;
arrIdsCategoriesFiltersGeneric3 = tblCategoriesDataObject.hasOwnProperty('_arrIdsCategoriesFiltersGeneric3') === true && tblCategoriesDataObject._arrIdsCategoriesFiltersGeneric3 ? tblCategoriesDataObject._arrIdsCategoriesFiltersGeneric3 : arrIdsCategoriesFiltersGeneric3;
arrIdsCategoriesFiltersGeneric4 = tblCategoriesDataObject.hasOwnProperty('_arrIdsCategoriesFiltersGeneric4') === true && tblCategoriesDataObject._arrIdsCategoriesFiltersGeneric4 ? tblCategoriesDataObject._arrIdsCategoriesFiltersGeneric4 : arrIdsCategoriesFiltersGeneric4;
arrIdsCategoriesFiltersGeneric5 = tblCategoriesDataObject.hasOwnProperty('_arrIdsCategoriesFiltersGeneric5') === true && tblCategoriesDataObject._arrIdsCategoriesFiltersGeneric5 ? tblCategoriesDataObject._arrIdsCategoriesFiltersGeneric5 : arrIdsCategoriesFiltersGeneric5;
arrIdsCategoriesFiltersGeneric6 = tblCategoriesDataObject.hasOwnProperty('_arrIdsCategoriesFiltersGeneric6') === true && tblCategoriesDataObject._arrIdsCategoriesFiltersGeneric6 ? tblCategoriesDataObject._arrIdsCategoriesFiltersGeneric6 : arrIdsCategoriesFiltersGeneric6;
arrIdsCategoriesFiltersGeneric5 = tblCategoriesDataObject.hasOwnProperty('_arrIdsCategoriesFiltersGeneric5') === true && tblCategoriesDataObject._arrIdsCategoriesFiltersGeneric5 ? tblCategoriesDataObject._arrIdsCategoriesFiltersGeneric5 : arrIdsCategoriesFiltersGeneric5;
arrIdsCategoriesFiltersGeneric6 = tblCategoriesDataObject.hasOwnProperty('_arrIdsCategoriesFiltersGeneric6') === true && tblCategoriesDataObject._arrIdsCategoriesFiltersGeneric6 ? tblCategoriesDataObject._arrIdsCategoriesFiltersGeneric6 : arrIdsCategoriesFiltersGeneric6;
arrIdsCategoriesFiltersGeneric7 = tblCategoriesDataObject.hasOwnProperty('_arrIdsCategoriesFiltersGeneric7') === true && tblCategoriesDataObject._arrIdsCategoriesFiltersGeneric7 ? tblCategoriesDataObject._arrIdsCategoriesFiltersGeneric7 : arrIdsCategoriesFiltersGeneric7;
arrIdsCategoriesFiltersGeneric8 = tblCategoriesDataObject.hasOwnProperty('_arrIdsCategoriesFiltersGeneric8') === true && tblCategoriesDataObject._arrIdsCategoriesFiltersGeneric8 ? tblCategoriesDataObject._arrIdsCategoriesFiltersGeneric8 : arrIdsCategoriesFiltersGeneric8;
arrIdsCategoriesFiltersGeneric9 = tblCategoriesDataObject.hasOwnProperty('_arrIdsCategoriesFiltersGeneric9') === true && tblCategoriesDataObject._arrIdsCategoriesFiltersGeneric9 ? tblCategoriesDataObject._arrIdsCategoriesFiltersGeneric9 : arrIdsCategoriesFiltersGeneric9;
arrIdsCategoriesFiltersGeneric10 = tblCategoriesDataObject.hasOwnProperty('_arrIdsCategoriesFiltersGeneric10') === true && tblCategoriesDataObject._arrIdsCategoriesFiltersGeneric10 ? tblCategoriesDataObject._arrIdsCategoriesFiltersGeneric10 : arrIdsCategoriesFiltersGeneric10;
